# Generated by Django 4.1.7 on 2023-03-19 16:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("quotation", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="quotelineitem",
            old_name="quote",
            new_name="quote_option",
        ),
    ]
