# Generated by Django 4.1.7 on 2023-03-20 10:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quotation", "0003_quote_search_params"),
    ]

    operations = [
        migrations.AddField(
            model_name="quote",
            name="original_input",
            field=models.TextField(blank=True, null=True),
        ),
    ]
