# Generated by Django 4.1.7 on 2023-03-20 16:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quotation", "0004_quote_original_input"),
    ]

    operations = [
        migrations.AddField(
            model_name="quotelineitem",
            name="goods",
            field=models.TextField(blank=True, null=True),
        ),
    ]
