# Generated by Django 4.1.7 on 2023-03-20 16:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rates", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="surcharge",
            name="surcharge_type",
            field=models.CharField(
                choices=[
                    ("danger", "Surcharge for Dangerous Goods"),
                    ("customs", "Surcharge for Customs Fee"),
                    ("fragile", "Surcharge for Fragile Goods"),
                ],
                max_length=10,
            ),
        ),
    ]
