# Generated by Django 4.1.7 on 2023-03-20 16:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rates", "0002_alter_surcharge_surcharge_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mainrate",
            name="valid_from",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="mainrate",
            name="valid_until",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="surcharge",
            name="valid_from",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="surcharge",
            name="valid_until",
            field=models.DateField(),
        ),
    ]
